### ISSUE TITLE
Failed to change env 

### ISSUE THREAD

**Issue by ryanaidilp** [pingbird/puro#21]
**Issue with Using Puro on MacBook - Seeking Help**

Hey there! 👋 I'm facing an issue while trying to utilize Puro on my MacBook as a replacement for fvm. Here's what I did:

1. I created environments for stable and legacy_3310 (version 3.3.10) successfully.
2. However, when I run `puro use legacy_3310`, I encounter the following error:

![image](https://github.com/pingbird/puro/assets/43450710/21f1c677-0560-4850-b1f4-1dacc911ca1b)

Additionally, I noticed that whenever I open a new VSCode instance, I can't use `puro` directly in my terminal unless I manually run `source ~/.zprofile`. I attempted moving the export path declaration to `~/.zshrc`, but unfortunately, it didn't resolve the issue either. 

I would greatly appreciate any assistance on how to ensure Puro is loaded automatically without needing to run `source ~/.zprofile` each time.

Looking forward to your support! Thank you! 🙏

**Comment by pingbird** [comment]
The first error indicates puro was unable to parse your settings.json file, could you post it? VSCode has its own JSON grammar with comments and stuff that I wrote a library to parse, so its probably a bug in that.

As far as the environment variable stuff just logging out should work, updating the PATH is a mess unfortunately, `.zshrc` is loaded every time you start an interactive shell but not for non-interactive shells. Puro updates `.zprofile` by default but it might not carry over to desktop applications until you've logged back in.

**Comment by ryanaidilp** [comment]
> The first error indicates puro was unable to parse your settings.json file, could you post it? VSCode has its own JSON grammar with comments and stuff that I wrote a library to parse, so its probably a bug in that.
> 
> As far as the environment variable stuff just logging out should work, updating the PATH is a mess unfortunately, `.zshrc` is loaded every time you start an interactive shell but not for non-interactive shells. Puro updates `.zprofile` by default but it might not carry over to desktop applications until you've logged back in.

Here is my `settings.json`

```json
{
    "workbench.colorTheme": "One Dark Pro Mix",
    "dart.flutterSdkPath": ".fvm/flutter_sdk",
    "files.watcherExclude": {
        "**/.dart_tool": true,
        "**/.fvm": true,
    },
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        "**/*.code-search": true,
        "**/.fvm": true,
    },
    "[dart]": {
        "editor.formatOnSave": true,
        "editor.formatOnType": true,
        "editor.rulers": [
            80
        ],
        "editor.selectionHighlight": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.suggestSelection": "first",
        "editor.tabCompletion": "onlySnippets",
        "editor.wordBasedSuggestions": false
    },
    "workbench.iconTheme": "material-icon-theme",
    "terminal.integrated.fontFamily": "\"MesloLGS NF\"",
    "files.autoSave": "afterDelay",
    "git.autofetch": true,
    "explorer.confirmDelete": false,
    "git.confirmSync": false,
    "dart.debugExternalPackageLibraries": false,
    "dart.debugSdkLibraries": false,
    "git.openRepositoryInParentFolders": "never",
}
```

Despite restarting my Mac, the ~/.zprofile configuration of Puro is still not loading automatically. As a result, I still need to run source ~/.zprofile before being able to use Puro. Any insights on how to resolve this issue would be greatly appreciated. Thank you for answering! 🙏

![image](https://github.com/pingbird/puro/assets/43450710/893bf0f2-d3db-46a9-a33e-d0fe9a955fd8)

**Comment by pingbird** [comment]
The bug with settings.json should be fixed in the next release, it was just the trailing commas :cry:

Try moving the exports to `~/.zshenv`

**Comment by ryanaidilp** [comment]
> The bug with settings.json should be fixed in the next release, it was just the trailing commas 😢
> 
> Try moving the exports to `~/.zshenv`

Thank you for your prompt response! I really appreciate it.

I tried moving the exports to ~/.zshenv as suggested, but unfortunately, I'm still encountering the same error. However, I can confirm that running `source ~/.zprofile` first allows me to use Puro without any issues.

I'm eagerly looking forward to the next update, as Puro has been an excellent replacement for fvm due to its minimal resource usage. Hoping that the upcoming release will address and resolve all these bugs.

Thank you once again for your help, and I'll be eagerly awaiting the fix! 🙏🚀

**Comment by ondanplatform** [comment]
I have same error 

```
(base) mirzali@Mirzalis-MacBook-Pro my_project % puro use stable

[E] Exception while installing IntelliJ config
[E] Unsupported operation: Cannot extract a non-Windows file path from a file URI with an authority
    #0      _Uri._toFilePath (dart:core/uri.dart:2862)
    #1      _Uri.toFilePath (dart:core/uri.dart:2857)
    #2      IntelliJConfig.load (package:puro/src/workspace/intellij.dart:290)
    #3      installIdeConfigs.<anonymous closure> (package:puro/src/workspace/install.dart:28)
    #4      runOptional (package:puro/src/logger.dart:173)
    #5      installIdeConfigs (package:puro/src/workspace/install.dart:24)
    #6      installWorkspaceEnvironment.<anonymous closure> (package:puro/src/workspace/install.dart:107)
    #7      runOptional (package:puro/src/logger.dart:173)
    #8      installWorkspaceEnvironment (package:puro/src/workspace/install.dart:104)
    <asynchronous suspension>
    #9      switchEnvironment (package:puro/src/workspace/install.dart:133)
    <asynchronous suspension>
    #10     EnvUseCommand.run (package:puro/src/commands/env_use.dart:83)
    <asynchronous suspension>
    #11     CommandRunner.runCommand (package:args/command_runner.dart:212)
    <asynchronous suspension>
    #12     main (package:puro/src/cli.dart:234)
    <asynchronous suspension>
```

**Comment by pingbird** [comment]
@ondanplatform That is a separate error, could you post the contents of your `.idea/libraries/Dart_SDK.xml` file?

**Comment by pingbird** [comment]
@ryanaidilp New zsh shells should always be sourcing .zshenv and .zshrc, if that isn't working I can offer some troubleshooting steps but this is unrelated to puro:

1. Make sure you are actually using zsh, `echo $SHELL` should tell you definitively
2. Make sure `ZDOTDIR` is unset
3. Make sure `NO_RCS` is unset
4. Try adding `set -x` to the top of the config files and see if their commands are printed, maybe it's erroring silently

**Comment by ryanaidilp** [comment]
> @ryanaidilp New zsh shells should always be sourcing .zshenv and .zshrc, if that isn't working I can offer some troubleshooting steps but this is unrelated to puro:
> 
> 1. Make sure you are actually using zsh, `echo $SHELL` should tell you definitively
> 2. Make sure `ZDOTDIR` is unset
> 3. Make sure `NO_RCS` is unset
> 4. Try adding `set -x` to the top of the config files and see if their commands are printed, maybe it's erroring silently

Thank you for the troubleshooting steps! I've tried everything from step one to step four, but unfortunately, the puro is still not loading automatically without running `source ~/.zprofile` first. Here are my findings based on the steps:

1. I confirmed that I am using zsh as my shell (`echo $SHELL` returned `/bin/zsh`).
2. `ZDOTDIR` is unset.
3. `NO_RCS` is also unset.
4. I added `set -x` to the top of the config files (`~/.zshenv` and `~/.zshrc`), but no commands were printed, and there were no visible errors.

I'm wondering if there could be any other possible reasons for this behavior? I appreciate any further suggestions or insights to resolve this issue.

Thanks again for your assistance!

**Comment by emanuel-braz** [comment]
same here

**Comment by pingbird** [comment]
Unfortunately there is nothing else I can do, zsh is supposed to source those files automatically and it doesn't appear to have anything to do with Puro

**Comment by pingbird** [comment]
Makes sense why it interfered with puro, you should never overwrite the whole PATH variable and append new stuff instead, not sure why `set -x` didn't show that export command.

**Comment by steinmetz** [comment]
I just upgraded puro and still get the same error:
![image](https://github.com/pingbird/puro/assets/3587083/1fca84a9-1ab5-4367-80ea-8674a06e357b)

**Comment by pingbird** [comment]
@steinmetz that's not the same error, could you create a new issue and include your settings.json file?
